# Generated by Django 4.0.5 on 2022-06-18 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WideEvents', '0002_event_group_of_recipients_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remind_before',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
