# Generated by Django 4.0.5 on 2022-06-18 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WideEvents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group_of_recipients',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='notes',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
